[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "udisk_monitor"
version = "0.0.1"
dependencies = [
  "pygobject",
]
requires-python = ">= 3.10"

[project.scripts]
udisk_monitor = "udisk_monitor:main"
